/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedThesisRouteImport } from './routes/_authenticated.thesis'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedHuntRouteImport } from './routes/_authenticated.hunt'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCriteriaRouteImport } from './routes/_authenticated.criteria'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated.companies'
import { Route as AuthenticatedFounderIdRouteImport } from './routes/_authenticated.founder.$id'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated.companies.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedThesisRoute = AuthenticatedThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHuntRoute = AuthenticatedHuntRouteImport.update({
  id: '/hunt',
  path: '/hunt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCriteriaRoute = AuthenticatedCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFounderIdRoute = AuthenticatedFounderIdRouteImport.update({
  id: '/founder/$id',
  path: '/founder/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/criteria': typeof AuthenticatedCriteriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hunt': typeof AuthenticatedHuntRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/thesis': typeof AuthenticatedThesisRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/founder/$id': typeof AuthenticatedFounderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/criteria': typeof AuthenticatedCriteriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hunt': typeof AuthenticatedHuntRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/thesis': typeof AuthenticatedThesisRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/founder/$id': typeof AuthenticatedFounderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/criteria': typeof AuthenticatedCriteriaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hunt': typeof AuthenticatedHuntRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/thesis': typeof AuthenticatedThesisRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/_authenticated/founder/$id': typeof AuthenticatedFounderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/companies'
    | '/criteria'
    | '/dashboard'
    | '/hunt'
    | '/settings'
    | '/thesis'
    | '/companies/$id'
    | '/founder/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/companies'
    | '/criteria'
    | '/dashboard'
    | '/hunt'
    | '/settings'
    | '/thesis'
    | '/companies/$id'
    | '/founder/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/companies'
    | '/_authenticated/criteria'
    | '/_authenticated/dashboard'
    | '/_authenticated/hunt'
    | '/_authenticated/settings'
    | '/_authenticated/thesis'
    | '/_authenticated/companies/$id'
    | '/_authenticated/founder/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/thesis': {
      id: '/_authenticated/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof AuthenticatedThesisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hunt': {
      id: '/_authenticated/hunt'
      path: '/hunt'
      fullPath: '/hunt'
      preLoaderRoute: typeof AuthenticatedHuntRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/criteria': {
      id: '/_authenticated/criteria'
      path: '/criteria'
      fullPath: '/criteria'
      preLoaderRoute: typeof AuthenticatedCriteriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/founder/$id': {
      id: '/_authenticated/founder/$id'
      path: '/founder/$id'
      fullPath: '/founder/$id'
      preLoaderRoute: typeof AuthenticatedFounderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
  }
}

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedCriteriaRoute: typeof AuthenticatedCriteriaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHuntRoute: typeof AuthenticatedHuntRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedThesisRoute: typeof AuthenticatedThesisRoute
  AuthenticatedFounderIdRoute: typeof AuthenticatedFounderIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedCriteriaRoute: AuthenticatedCriteriaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHuntRoute: AuthenticatedHuntRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedThesisRoute: AuthenticatedThesisRoute,
  AuthenticatedFounderIdRoute: AuthenticatedFounderIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
